### ISSUE TITLE
"Failed to start a track"

### ISSUE THREAD

**Issue by Lypheo** [RblSb/SyncTube-octosubs#1]
I tried to set the plugin up exactly as per the instructions, however, when I try to use it, it logs
![grafik](https://user-images.githubusercontent.com/45497420/101340011-76cbc580-387f-11eb-976d-8c3de87e4c03.png)

Sorry if this is not much to go on, I’m very inexperienced with webdev, so any pointers as to what I might be doing wrong would be greatly appreciated!

**Comment by RblSb** [comment]
Is this happen when you trying to add video? You can send subs file in archive and say browser and browser version, i will check. Installation seems correct btw, probably something wrong with browser support or subtitles.

**Comment by Lypheo** [comment]
> Is this happen when you trying to add video?

Yes. 
ASS file: http://maven.whatbox.ca:11665/ddl/aot/test.ass (.mp4 is the video is was testing with)
Happens both in latest Edge and Firefox 83.0.
Thanks a lot for taking a look!

**Comment by RblSb** [comment]
Thanks for your report, let me know if you still/will have problems!

**Comment by Lypheo** [comment]
Thanks, but the error persisted for me.
This fixed it for me (don’t know haxe so I edited the js file):
```git diff
diff --git a/build/server.js b/build/server.js
index 4df6b9f..45164db 100644
--- a/build/server.js
+++ b/build/server.js
@@ -3575,10 +3575,7 @@ server_HttpServer.proxyRequest = function(url,req,res,fn) {
        if(url1.host == req.headers["host"]) {
                return null;
        }
-       if(url1.host.indexOf(":") != -1) {
-               url1.host = url1.host.split(":")[0];
-       }
-       var proxy = (url1.protocol == "https:" ? js_node_Https.request : js_node_Http.request)({ host : url1.host, port : Std.parseInt(url1.port), path : url1.pathname + url1.search, method : req.method},function(proxyReq) {
+       var proxy = (url1.protocol == "https:" ? js_node_Https.request : js_node_Http.request)({ host : url1.hostname, port : Std.parseInt(url1.port), path : url1.pathname + url1.search, method : req.method},function(proxyReq) {
                if(fn(proxyReq)) {
                        return;
                }
```

**Comment by RblSb** [comment]
> The key difference between url.host and url.hostname is that url.hostname does not include the port.

I guess because of
> Invalid host values assigned to the host property are ignored.

I cannot change url object and this behaviour only works in some nodejs versions. Thanks, moved to your solution x)
