### ISSUE TITLE
Does this plugin still work with the current SyncTube master? I couldn't get it to work.

### ISSUE THREAD

**Issue by spma1037** [RblSb/SyncTube-octosubs#2]
I used the current masters of both SyncTube and SyncTube-octosubs, but I couldn't get the subtitles to display. I could see the load on my computer increase after adding this plugin, though, so I suppose at least _something_ was working.

Is there any specific format or version of *.ass subtitles this plugin requires? I'm extracting and converting via ffmpeg if that helps any.

**Comment by RblSb** [comment]
Hi, it works. Currently you need to have ass/mp4 files on same url, try to add to playlist: `http://82.146.45.136/files/test.mp4`
It should load `http://82.146.45.136/files/test.ass` and show subs for you after plugin installation. I will add `subtitles url` field for this plugin soon.

**Comment by spma1037** [comment]
I couldn't get it to work.

My file structure is:

https://my.domain/ - SyncTube
https://my.domain/media/videoname.mp4 - Video file
https://my.domain/media/videoname.ass - Subtitles file

I'm using nginx as a reverse proxy if that changes anything.

Loading the video and opening the *.ass file displays the subtitles properly in VLC.

I tested it with Firefox and Chromium and neither worked.

**Comment by RblSb** [comment]
Thank you, i think this should be fixed now. Test latest commits from SyncTube and this plugin please.
